sudo: false
language: python
python: 2.7
cache:
  pip: true
  directories:
    - eggs
env:
  - PLONE_VERSION=4.2
  - PLONE_VERSION=4.3
install:
  - python bootstrap.py -c test-plone-$PLONE_VERSION.x.cfg
  - bin/buildout -c test-plone-$PLONE_VERSION.x.cfg annotate
  - bin/buildout -c test-plone-$PLONE_VERSION.x.cfg -N -q
script: bin/test
