sudo: false
language: python
python: 2.7
cache:
  directories:
    - buildout-cache
env:
  - PLONE_VERSION=4.2
  - PLONE_VERSION=4.3
install:
  - sed -ie "s#travis-4.x.cfg#travis-$PLONE_VERSION.x.cfg#" travis.cfg
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis.cfg
  - bin/buildout -c travis.cfg annotate
# Try this twice, to avoid a possible problem, on Plone 4.3.7 at
# least, with setuptools as directory instead of zipped egg.
  - bin/buildout -c travis.cfg -N -q || true
  - bin/buildout -c travis.cfg -N -q
script: bin/test
after_success: bin/coverage.sh && pip install -q coveralls && coveralls || true
